### ISSUE TITLE
Problem compiling in Step 4

### ISSUE THREAD

**Issue by stemania1** [OskarAsplin/react-ts-redux-oauth2-template#1]
Hi Oskar.   Nice tutorial, but I wasn't able to compile in Step 4!   I'm getting this error: "Module not found: Can't resolve '../../utils/hashUtils' in ...\features\authorization

This happens in the Authorization.tsx file.   I checked this several times and can't find the error.

I'm a complete noob at this, so apologies in advance if I'm missing something obvious.

Thanks!

**Comment by OskarAsplin** [comment]
Hi! Thanks for reaching out!

This error means that React can't find what it is looking for in the given path. In this case the path is '../../utils/hashUtils'. Make sure that you have created a folder named 'utils' in the 'src' folder and that the 'utils' folder contains the file 'hashUtils.ts' from the tutorial. The Authorization.tsx file should be in the 'authorization' folder, which is in the 'features' folder, which is in the 'src' folder. This usual way of writing a folder structure like this is: 'src/features/authorization'.

So to explain the relative path '../../utils/hashUtils': From the location of Authorization.tsx it goes up two folders (../../), and then goes into the utils folder (utils/) and there it looks for a file called hashUtils.

You can read more about this error here: https://stackoverflow.com/questions/44439205/cant-resolve-module-not-found-in-react-js

Let me know if this solves your problem.
